// Code generated by protoc-gen-go. DO NOT EDIT.
// source: raft.proto

package raft

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServerRole int32

const (
	ServerRole_FOLLOWER  ServerRole = 0
	ServerRole_CANDIDATE ServerRole = 1
	ServerRole_LEADER    ServerRole = 2
)

var ServerRole_name = map[int32]string{
	0: "FOLLOWER",
	1: "CANDIDATE",
	2: "LEADER",
}
var ServerRole_value = map[string]int32{
	"FOLLOWER":  0,
	"CANDIDATE": 1,
	"LEADER":    2,
}

func (x ServerRole) String() string {
	return proto.EnumName(ServerRole_name, int32(x))
}
func (ServerRole) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_raft_bb97dd21d0a1db76, []int{0}
}

type LogEntry struct {
	Term                 int32    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Index                int32    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogEntry) Reset()         { *m = LogEntry{} }
func (m *LogEntry) String() string { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()    {}
func (*LogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_bb97dd21d0a1db76, []int{0}
}
func (m *LogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEntry.Unmarshal(m, b)
}
func (m *LogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEntry.Marshal(b, m, deterministic)
}
func (dst *LogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEntry.Merge(dst, src)
}
func (m *LogEntry) XXX_Size() int {
	return xxx_messageInfo_LogEntry.Size(m)
}
func (m *LogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LogEntry proto.InternalMessageInfo

func (m *LogEntry) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *LogEntry) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type AppendEntriesParam struct {
	Term                 int32       `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId             string      `protobuf:"bytes,2,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	PrevLogIndex         int32       `protobuf:"varint,3,opt,name=prevLogIndex,proto3" json:"prevLogIndex,omitempty"`
	PrevLogTerm          int32       `protobuf:"varint,4,opt,name=prevLogTerm,proto3" json:"prevLogTerm,omitempty"`
	Entries              []*LogEntry `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit         int32       `protobuf:"varint,6,opt,name=leaderCommit,proto3" json:"leaderCommit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AppendEntriesParam) Reset()         { *m = AppendEntriesParam{} }
func (m *AppendEntriesParam) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesParam) ProtoMessage()    {}
func (*AppendEntriesParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_bb97dd21d0a1db76, []int{1}
}
func (m *AppendEntriesParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesParam.Unmarshal(m, b)
}
func (m *AppendEntriesParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesParam.Marshal(b, m, deterministic)
}
func (dst *AppendEntriesParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesParam.Merge(dst, src)
}
func (m *AppendEntriesParam) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesParam.Size(m)
}
func (m *AppendEntriesParam) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesParam.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesParam proto.InternalMessageInfo

func (m *AppendEntriesParam) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesParam) GetLeaderId() string {
	if m != nil {
		return m.LeaderId
	}
	return ""
}

func (m *AppendEntriesParam) GetPrevLogIndex() int32 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *AppendEntriesParam) GetPrevLogTerm() int32 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntriesParam) GetEntries() []*LogEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *AppendEntriesParam) GetLeaderCommit() int32 {
	if m != nil {
		return m.LeaderCommit
	}
	return 0
}

type AppendEntriesResult struct {
	Term                 int32    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntriesResult) Reset()         { *m = AppendEntriesResult{} }
func (m *AppendEntriesResult) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesResult) ProtoMessage()    {}
func (*AppendEntriesResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_bb97dd21d0a1db76, []int{2}
}
func (m *AppendEntriesResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesResult.Unmarshal(m, b)
}
func (m *AppendEntriesResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesResult.Marshal(b, m, deterministic)
}
func (dst *AppendEntriesResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesResult.Merge(dst, src)
}
func (m *AppendEntriesResult) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesResult.Size(m)
}
func (m *AppendEntriesResult) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesResult.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesResult proto.InternalMessageInfo

func (m *AppendEntriesResult) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RequestVoteParam struct {
	Term                 int32    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId          string   `protobuf:"bytes,2,opt,name=candidateId,proto3" json:"candidateId,omitempty"`
	LastLogIndex         int32    `protobuf:"varint,3,opt,name=lastLogIndex,proto3" json:"lastLogIndex,omitempty"`
	LastLogTerm          int32    `protobuf:"varint,4,opt,name=lastLogTerm,proto3" json:"lastLogTerm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteParam) Reset()         { *m = RequestVoteParam{} }
func (m *RequestVoteParam) String() string { return proto.CompactTextString(m) }
func (*RequestVoteParam) ProtoMessage()    {}
func (*RequestVoteParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_bb97dd21d0a1db76, []int{3}
}
func (m *RequestVoteParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteParam.Unmarshal(m, b)
}
func (m *RequestVoteParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteParam.Marshal(b, m, deterministic)
}
func (dst *RequestVoteParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteParam.Merge(dst, src)
}
func (m *RequestVoteParam) XXX_Size() int {
	return xxx_messageInfo_RequestVoteParam.Size(m)
}
func (m *RequestVoteParam) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteParam.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteParam proto.InternalMessageInfo

func (m *RequestVoteParam) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteParam) GetCandidateId() string {
	if m != nil {
		return m.CandidateId
	}
	return ""
}

func (m *RequestVoteParam) GetLastLogIndex() int32 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *RequestVoteParam) GetLastLogTerm() int32 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

type RequestVoteResult struct {
	Term                 int32    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted          bool     `protobuf:"varint,2,opt,name=voteGranted,proto3" json:"voteGranted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteResult) Reset()         { *m = RequestVoteResult{} }
func (m *RequestVoteResult) String() string { return proto.CompactTextString(m) }
func (*RequestVoteResult) ProtoMessage()    {}
func (*RequestVoteResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_bb97dd21d0a1db76, []int{4}
}
func (m *RequestVoteResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteResult.Unmarshal(m, b)
}
func (m *RequestVoteResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteResult.Marshal(b, m, deterministic)
}
func (dst *RequestVoteResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteResult.Merge(dst, src)
}
func (m *RequestVoteResult) XXX_Size() int {
	return xxx_messageInfo_RequestVoteResult.Size(m)
}
func (m *RequestVoteResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteResult.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteResult proto.InternalMessageInfo

func (m *RequestVoteResult) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteResult) GetVoteGranted() bool {
	if m != nil {
		return m.VoteGranted
	}
	return false
}

func init() {
	proto.RegisterType((*LogEntry)(nil), "raft.LogEntry")
	proto.RegisterType((*AppendEntriesParam)(nil), "raft.AppendEntriesParam")
	proto.RegisterType((*AppendEntriesResult)(nil), "raft.AppendEntriesResult")
	proto.RegisterType((*RequestVoteParam)(nil), "raft.RequestVoteParam")
	proto.RegisterType((*RequestVoteResult)(nil), "raft.RequestVoteResult")
	proto.RegisterEnum("raft.ServerRole", ServerRole_name, ServerRole_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServerServiceClient is the client API for ServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerServiceClient interface {
	AppendEntries(ctx context.Context, in *AppendEntriesParam, opts ...grpc.CallOption) (*AppendEntriesResult, error)
	RequestVote(ctx context.Context, in *RequestVoteParam, opts ...grpc.CallOption) (*RequestVoteResult, error)
}

type serverServiceClient struct {
	cc *grpc.ClientConn
}

func NewServerServiceClient(cc *grpc.ClientConn) ServerServiceClient {
	return &serverServiceClient{cc}
}

func (c *serverServiceClient) AppendEntries(ctx context.Context, in *AppendEntriesParam, opts ...grpc.CallOption) (*AppendEntriesResult, error) {
	out := new(AppendEntriesResult)
	err := c.cc.Invoke(ctx, "/raft.ServerService/appendEntries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverServiceClient) RequestVote(ctx context.Context, in *RequestVoteParam, opts ...grpc.CallOption) (*RequestVoteResult, error) {
	out := new(RequestVoteResult)
	err := c.cc.Invoke(ctx, "/raft.ServerService/requestVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerServiceServer is the server API for ServerService service.
type ServerServiceServer interface {
	AppendEntries(context.Context, *AppendEntriesParam) (*AppendEntriesResult, error)
	RequestVote(context.Context, *RequestVoteParam) (*RequestVoteResult, error)
}

func RegisterServerServiceServer(s *grpc.Server, srv ServerServiceServer) {
	s.RegisterService(&_ServerService_serviceDesc, srv)
}

func _ServerService_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServiceServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.ServerService/AppendEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServiceServer).AppendEntries(ctx, req.(*AppendEntriesParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerService_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServiceServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.ServerService/RequestVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServiceServer).RequestVote(ctx, req.(*RequestVoteParam))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "raft.ServerService",
	HandlerType: (*ServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "appendEntries",
			Handler:    _ServerService_AppendEntries_Handler,
		},
		{
			MethodName: "requestVote",
			Handler:    _ServerService_RequestVote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raft.proto",
}

func init() { proto.RegisterFile("raft.proto", fileDescriptor_raft_bb97dd21d0a1db76) }

var fileDescriptor_raft_bb97dd21d0a1db76 = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0x26, 0x5b, 0xdb, 0xa5, 0x2f, 0xeb, 0x14, 0x0c, 0x82, 0xd0, 0x53, 0x14, 0x2e, 0x15, 0x87,
	0x1e, 0x06, 0x5c, 0x91, 0xb2, 0x26, 0xa0, 0x48, 0x11, 0xab, 0xcc, 0x04, 0x12, 0x37, 0x93, 0xbc,
	0x95, 0x48, 0x4d, 0x1c, 0x6c, 0xb7, 0x8c, 0x7f, 0x82, 0x1b, 0xff, 0x1b, 0x7f, 0x0e, 0x8a, 0x9d,
	0x0e, 0x6f, 0x2d, 0x5c, 0x22, 0x7f, 0x9f, 0xdf, 0xaf, 0xef, 0x8b, 0x1f, 0x80, 0x60, 0xd7, 0x6a,
	0xde, 0x0a, 0xae, 0x38, 0x19, 0x74, 0xe7, 0xe8, 0x15, 0xb8, 0x39, 0x5f, 0xa5, 0x8d, 0x12, 0x3f,
	0x08, 0x81, 0x81, 0x42, 0x51, 0x07, 0x4e, 0xe8, 0xcc, 0x86, 0x54, 0x9f, 0xc9, 0x63, 0x18, 0x56,
	0x4d, 0x89, 0x37, 0xc1, 0x91, 0x26, 0x0d, 0x88, 0x7e, 0x3b, 0x40, 0xe2, 0xb6, 0xc5, 0xa6, 0xec,
	0x32, 0x2b, 0x94, 0x4b, 0x26, 0x58, 0x7d, 0xb0, 0xc0, 0x14, 0xdc, 0x35, 0xb2, 0x12, 0x45, 0x56,
	0xea, 0x1a, 0x63, 0x7a, 0x8b, 0x49, 0x04, 0xa7, 0xad, 0xc0, 0x6d, 0xce, 0x57, 0x99, 0xee, 0x71,
	0xac, 0xf3, 0xee, 0x70, 0x24, 0x04, 0xaf, 0xc7, 0x57, 0x5d, 0xe9, 0x81, 0x0e, 0xb1, 0x29, 0x32,
	0x83, 0x13, 0x34, 0x53, 0x04, 0xc3, 0xf0, 0x78, 0xe6, 0x9d, 0x9f, 0xcd, 0xb5, 0xcc, 0x9d, 0x2e,
	0xba, 0xbb, 0xee, 0xfa, 0x99, 0xde, 0x0b, 0x5e, 0xd7, 0x95, 0x0a, 0x46, 0xa6, 0x9f, 0xcd, 0x45,
	0x0b, 0x78, 0x74, 0x47, 0x19, 0x45, 0xb9, 0x59, 0xab, 0x83, 0xd2, 0x02, 0x38, 0x91, 0x9b, 0xa2,
	0x40, 0x29, 0xb5, 0x32, 0x97, 0xee, 0x60, 0xf4, 0xd3, 0x01, 0x9f, 0xe2, 0xb7, 0x0d, 0x4a, 0xf5,
	0x91, 0x2b, 0xfc, 0xb7, 0x3b, 0x21, 0x78, 0x05, 0x6b, 0xca, 0xaa, 0x64, 0x0a, 0x6f, 0x0d, 0xb2,
	0x29, 0x3d, 0x33, 0x93, 0xea, 0xbe, 0x47, 0x36, 0xd7, 0x55, 0xe9, 0xb1, 0xed, 0x91, 0x45, 0x45,
	0x19, 0x3c, 0xb4, 0xe6, 0xf9, 0x8f, 0xa6, 0x10, 0xbc, 0x2d, 0x57, 0xf8, 0x4e, 0xb0, 0x46, 0x61,
	0xd9, 0xeb, 0xb2, 0xa9, 0x17, 0xaf, 0x01, 0x3e, 0xa0, 0xd8, 0xa2, 0xa0, 0x7c, 0x8d, 0xe4, 0x14,
	0xdc, 0xb7, 0x97, 0x79, 0x7e, 0xf9, 0x29, 0xa5, 0xfe, 0x03, 0x32, 0x81, 0xf1, 0x22, 0x7e, 0x9f,
	0x64, 0x49, 0x7c, 0x95, 0xfa, 0x0e, 0x01, 0x18, 0xe5, 0x69, 0x9c, 0xa4, 0xd4, 0x3f, 0x3a, 0xff,
	0xe5, 0xc0, 0xc4, 0xe4, 0x75, 0xdf, 0xaa, 0x40, 0x92, 0xc0, 0x84, 0xd9, 0x4e, 0x93, 0xc0, 0xfc,
	0xb7, 0xfd, 0x87, 0x35, 0x7d, 0x76, 0xe0, 0xa6, 0x17, 0xf1, 0x06, 0x3c, 0xf1, 0x57, 0x19, 0x79,
	0x62, 0x22, 0xef, 0x9b, 0x3f, 0x7d, 0xba, 0xc7, 0x9b, 0xfc, 0x8b, 0xe7, 0x70, 0xc6, 0xc5, 0x6a,
	0x2e, 0xab, 0x9b, 0xef, 0x5f, 0x75, 0xcc, 0xc5, 0x98, 0xb2, 0x6b, 0xb5, 0xec, 0x76, 0x64, 0xe9,
	0x7c, 0xd6, 0x5b, 0xf2, 0x65, 0xa4, 0x57, 0xe6, 0xe5, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x17,
	0xf1, 0xf8, 0x03, 0x40, 0x03, 0x00, 0x00,
}
